In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('../datasets/iris.csv')

In [3]:
df.head()

SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [4]:
x=df.ix[:, 0:4].values

In [5]:
x[0:5]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])

In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
x_standard = StandardScaler().fit_transform(x)
x_standard[0:5]

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

In [8]:
cov_mat=np.cov(x_standard.T)

In [9]:
cov_mat

array([[ 1.00671141, -0.11010327,  0.87760486,  0.82344326],
       [-0.11010327,  1.00671141, -0.42333835, -0.358937  ],
       [ 0.87760486, -0.42333835,  1.00671141,  0.96921855],
       [ 0.82344326, -0.358937  ,  0.96921855,  1.00671141]])

In [10]:
df.corr()

SepalLength  SepalWidth  PetalLength  PetalWidth
SepalLength     1.000000   -0.109369     0.871754    0.817954
SepalWidth     -0.109369    1.000000    -0.420516   -0.356544
PetalLength     0.871754   -0.420516     1.000000    0.962757
PetalWidth      0.817954   -0.356544     0.962757    1.000000

In [11]:
eigenvalues, eigenvectors=np.linalg.eig(cov_mat)

In [12]:
eigenvalues

array([ 2.93035378,  0.92740362,  0.14834223,  0.02074601])

In [14]:
eigenvectors

array([[ 0.52237162, -0.37231836, -0.72101681,  0.26199559],
       [-0.26335492, -0.92555649,  0.24203288, -0.12413481],
       [ 0.58125401, -0.02109478,  0.14089226, -0.80115427],
       [ 0.56561105, -0.06541577,  0.6338014 ,  0.52354627]])

In [13]:
cov_mat[:,0]

array([ 1.00671141, -0.11010327,  0.87760486,  0.82344326])

In [15]:
eigenValSum=sum(eigenvalues)
eigenValSum

4.0268456375838948

In [16]:
varianceExplained=[(i/eigenValSum)*100 for i in sorted(eigenvalues, reverse=True)]

In [17]:
varianceExplained

[72.770452093801339, 23.03052326768065, 3.6838319576273775, 0.5151926808906323]

In [18]:
cumulativeVarianceExplained=np.cumsum(varianceExplained)

In [19]:
cumulativeVarianceExplained

array([  72.77045209,   95.80097536,   99.48480732,  100.        ])

In [21]:
eigenPairs=zip(eigenvalues, eigenvectors)
eigenPairs

[(2.9303537755893174,
  array([ 0.52237162, -0.37231836, -0.72101681,  0.26199559])),
 (0.92740362151734212,
  array([-0.26335492, -0.92555649,  0.24203288, -0.12413481])),
 (0.14834222648163944,
  array([ 0.58125401, -0.02109478,  0.14089226, -0.80115427])),
 (0.020746013995595943,
  array([ 0.56561105, -0.06541577,  0.6338014 ,  0.52354627]))]

In [22]:
Pmatrix=np.hstack((eigenPairs[0][1].reshape(4,1),
                   eigenPairs[1][1].reshape(4,1)
                  ))

In [23]:
Pmatrix

array([[ 0.52237162, -0.26335492],
       [-0.37231836, -0.92555649],
       [-0.72101681,  0.24203288],
       [ 0.26199559, -0.12413481]])

In [28]:
x_standard.dot(Pmatrix)

array([[-0.2316583 , -0.87967436],
       [ 0.07253025,  0.25502854],
       [-0.18536908, -0.12326756],
       [-0.24451042,  0.15034585],
       [-0.38110853, -1.06194072],
       [-0.44050933, -1.82346152],
       [-0.42753067, -0.52226744],
       [-0.24979851, -0.61982431],
       [-0.15778746,  0.62875583],
       [-0.08907179,  0.07093576],
       [-0.2550866 , -1.38999448],
       [-0.41738895, -0.54224064],
       [-0.02520974,  0.30325906],
       [-0.21867964,  0.42151973],
       [-0.13737131, -2.20145476],
       [-0.59940097, -3.01760131],
       [-0.27650482, -1.878515  ],
       [-0.19721296, -0.89599473],
       [-0.19891512, -1.6886951 ],
       [-0.49668081, -1.52476091],
       [-0.07862214, -0.71993819],
       [-0.3760799 , -1.32690476],
       [-0.47028264, -0.98935358],
       [-0.07901452, -0.45899233],
       [-0.54039234, -0.50095053],
       [ 0.05382265,  0.25064512],
       [-0.22190896, -0.63870169],
       [-0.20936477, -0.89782114],
       [-0.08220807,

In [29]:
x_standard[0].dot(Pmatrix)

array([-0.2316583 , -0.87967436])

This dies all the above shit in a diferent way

In [30]:
from sklearn.decomposition import PCA

In [40]:
pca=PCA(n_components=2)

In [41]:
pca.fit_transform(x_standard)

array([[ -2.26454173e+00,  -5.05703903e-01],
       [ -2.08642550e+00,   6.55404729e-01],
       [ -2.36795045e+00,   3.18477311e-01],
       [ -2.30419716e+00,   5.75367713e-01],
       [ -2.38877749e+00,  -6.74767397e-01],
       [ -2.07053681e+00,  -1.51854856e+00],
       [ -2.44571134e+00,  -7.45626750e-02],
       [ -2.23384186e+00,  -2.47613932e-01],
       [ -2.34195768e+00,   1.09514636e+00],
       [ -2.18867576e+00,   4.48629048e-01],
       [ -2.16348656e+00,  -1.07059558e+00],
       [ -2.32737775e+00,  -1.58587455e-01],
       [ -2.22408272e+00,   7.09118158e-01],
       [ -2.63971626e+00,   9.38281982e-01],
       [ -2.19229151e+00,  -1.88997851e+00],
       [ -2.25146521e+00,  -2.72237108e+00],
       [ -2.20275048e+00,  -1.51375028e+00],
       [ -2.19017916e+00,  -5.14304308e-01],
       [ -1.89407429e+00,  -1.43111071e+00],
       [ -2.33994907e+00,  -1.15803343e+00],
       [ -1.91455639e+00,  -4.30465163e-01],
       [ -2.20464540e+00,  -9.52457317e-01],
       [ -

In [42]:
pca.get_covariance()

array([[ 0.97140471, -0.10037114,  0.86489005,  0.85560646],
       [-0.10037114,  0.99726417, -0.41637465, -0.37038414],
       [ 0.86489005, -0.41637465,  1.03941772,  0.93051689],
       [ 0.85560646, -0.37038414,  0.93051689,  0.99191341]])