In [55]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.decomposition import PCA

In [10]:
df=pd.read_csv('../datasets/votes.csv', index_col=0)
df

Class   V1   V2   V3   V4   V5   V6   V7   V8   V9  V10  V11  V12  \
1    republican    n    y    n    y    y    y    n    n    n    y  NaN    y   
2    republican    n    y    n    y    y    y    n    n    n    n    n    y   
3      democrat  NaN    y    y  NaN    y    y    n    n    n    n    y    n   
4      democrat    n    y    y    n  NaN    y    n    n    n    n    y    n   
5      democrat    y    y    y    n    y    y    n    n    n    n    y  NaN   
6      democrat    n    y    y    n    y    y    n    n    n    n    n    n   
7      democrat    n    y    n    y    y    y    n    n    n    n    n    n   
8    republican    n    y    n    y    y    y    n    n    n    n    n    n   
9    republican    n    y    n    y    y    y    n    n    n    n    n    y   
10     democrat    y    y    y    n    n    n    y    y    y    n    n    n   
11   republican    n    y    n    y    y    n    n    n    n    n  NaN  NaN   
12   republican    n    y    n    y    y    y    n    n    n    n    y  NaN   
13     democrat    n    y    y    n    n    n    y    y    y    n    n    n   
14     democrat    y    y    y    n    n    y    y    y  NaN    y    y  NaN   
15   republican    n    y    n    y    y    y    n    n    n    n    n    y   
16   republican    n    y    n    y    y    y    n    n    n    y    n    y   
17     democrat    y    n    y    n    n    y    n    y  NaN    y    y    y   
18     democrat    y  NaN    y    n    n    n    y    y    y    n    n    n   
19   republican    n    y    n    y    y    y    n    n    n    n    n  NaN   
20     democrat    y    y    y    n    n    n    y    y    y    n    y    n   
21     democrat    y    y    y    n    n  NaN    y    y    n    n    y    n   
22     democrat    y    y    y    n    n    n    y    y    y    n    n    n   
23     democrat    y  NaN    y    n    n    n    y    y    y    n    n  NaN   
24     democrat    y    y    y    n    n    n    y    y    y    n    n    n   
25     democrat    y    n    y    n    n    n    y    y    y    n    n    n   
26     democrat    y    n    y    n    n    n    y    y    y    y    n    n   
27     democrat    y    n    y    n    n    n    y    y    y    n    y    n   
28     democrat    y    y    y    n    n    n    y    y    y    n    y    n   
29   republican    y    n    n    y    y    n    y    y    y    n    n    y   
30     democrat    y    y    y    n    n    n    y    y    y    n    y    n   
..          ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
406  republican    n    n    n    y    y    y    n    n    n    n    n    y   
407    democrat    y    n    y    n    y    y    n    n    y    y    n    n   
408    democrat    n    n    n    y    y    y    n    n    n    n    y    y   
409    democrat    y    n    y    n    n    y    y    y    y    n    n    y   
410  republican    n    n    n    y    y    y    n    n    n    n    n    y   
411  republican    n    n    n    y    y    y    n    n    n    n    y    y   
412    democrat    y    n    y    n    n    y    y    y    y    y    y    n   
413  republican    n    n    n    y    y    y    n    n    n    y    n    y   
414  republican    y    y    y    y    y    y    y    y    n    y  NaN  NaN   
415    democrat    y    y    y    n    n    n    y    y    y    n    n    n   
416    democrat    n    y    y    n    n    y    y    y  NaN    y    n    n   
417  republican    y    y    n    y    y    y    n    n    n    y    n    n   
418    democrat    y    y    y    n    n    n    y    y    y    y    y    n   
419    democrat    y    y    y    n    n    n    y    y    n    y    n    n   
420    democrat    y    y    y    n    n    n    y    y    y    n    n    n   
421  republican    y    y    y    y    y    y    y    y    n    y    n    n   
422    democrat    n    y    y    n    y    y    y    y    n    n    y    n   
423    democrat    n    n    y    n    n    y    y    y    y    n    y    n   
424    democrat    n    y    y    n    n    y    y    y    y

In [11]:
y=df.Class

In [12]:
for col in df.columns:
    df[col]=df[col].apply(lambda x: 1 if x=='y' else 0)

In [15]:
x=df[[col for col in df.columns if col != 'Class']]

In [16]:
x.head()

V1  V2  V3  V4  V5  V6  V7  V8  V9  V10  V11  V12  V13  V14  V15  V16
1   0   1   0   1   1   1   0   0   0    1    0    1    1    1    0    1
2   0   1   0   1   1   1   0   0   0    0    0    1    1    1    0    0
3   0   1   1   0   1   1   0   0   0    0    1    0    1    1    0    0
4   0   1   1   0   0   1   0   0   0    0    1    0    1    0    0    1
5   1   1   1   0   1   1   0   0   0    0    1    0    1    1    1    1

In [17]:
from sklearn.preprocessing import StandardScaler

In [20]:
napolean=StandardScaler().fit_transform(x)
napolean.shape

(435, 16)

In [22]:
covariance_matrix=np.cov(napolean.T)
covariance_matrix.shape

(16, 16)

In [23]:
eignvalues, eigenvectors=np.linalg.eig(covariance_matrix)

In [26]:
eignvalues

array([ 7.102243  ,  1.44867882,  1.1998064 ,  0.88126251,  0.8248454 ,
        0.7380054 ,  0.14086407,  0.21188391,  0.61036665,  0.27622346,
        0.31858994,  0.35967328,  0.41340487,  0.54030753,  0.51431461,
        0.45639653])

In [25]:
eigenvectors.shape

(16, 16)

In [27]:
eigenpairs=zip(eignvalues, eigenvectors)

In [28]:
eigenpairs

[(7.1022429960917224,
  array([-0.18803934, -0.19357121,  0.07328808,  0.51751543,  0.35845006,
          0.62089874, -0.05713493, -0.00747574,  0.15602045, -0.03613906,
         -0.07010134, -0.20296072,  0.12290505,  0.07348099,  0.20525446,
         -0.04760145])),
 (1.4486788186332424,
  array([ 0.05231849, -0.5860793 , -0.23045319,  0.37516036,  0.12646973,
         -0.55398342,  0.01855198, -0.10910015,  0.10486865,  0.0799821 ,
          0.0801356 , -0.13259865, -0.06581724,  0.07925709, -0.00808044,
          0.26963501])),
 (1.1998063964339236,
  array([-0.29660826, -0.08013044, -0.16884543, -0.01308925,  0.10990706,
          0.03068335, -0.2133564 , -0.06665988, -0.17958811, -0.23883742,
          0.56681358,  0.45295072,  0.08181081, -0.3596669 ,  0.23464645,
          0.08418781])),
 (0.88126250977162834,
  array([ 0.31510691,  0.1422561 ,  0.07340739,  0.13936979, -0.00770719,
         -0.05450439, -0.39727071,  0.4526401 ,  0.17904898, -0.55964437,
          0.01205996, 

In [30]:
for i in sorted(eigenpairs, reverse=True):
    print i

(7.1022429960917224, array([-0.18803934, -0.19357121,  0.07328808,  0.51751543,  0.35845006,
        0.62089874, -0.05713493, -0.00747574,  0.15602045, -0.03613906,
       -0.07010134, -0.20296072,  0.12290505,  0.07348099,  0.20525446,
       -0.04760145]))
(1.4486788186332424, array([ 0.05231849, -0.5860793 , -0.23045319,  0.37516036,  0.12646973,
       -0.55398342,  0.01855198, -0.10910015,  0.10486865,  0.0799821 ,
        0.0801356 , -0.13259865, -0.06581724,  0.07925709, -0.00808044,
        0.26963501]))
(1.1998063964339236, array([-0.29660826, -0.08013044, -0.16884543, -0.01308925,  0.10990706,
        0.03068335, -0.2133564 , -0.06665988, -0.17958811, -0.23883742,
        0.56681358,  0.45295072,  0.08181081, -0.3596669 ,  0.23464645,
        0.08418781]))
(0.88126250977162834, array([ 0.31510691,  0.1422561 ,  0.07340739,  0.13936979, -0.00770719,
       -0.05450439, -0.39727071,  0.4526401 ,  0.17904898, -0.55964437,
        0.01205996,  0.0780124 , -0.11191782,  0.25270932

In [31]:
eignsums=sum(eignvalues)
eignsums

16.036866359446996

In [32]:
for eig in sorted(eigenpairs, reverse=True):
    print eig[0]/eignsums

0.442869750044
0.0903342826562
0.0748155138006
0.054952288684
0.051434325249
0.0460193020622
0.0380602190202
0.033691590004
0.0320707676532
0.0284592089754
0.0257784068163
0.022427902783
0.0198660966226
0.0172242789882
0.0132123011793
0.00878376546217


In [35]:
np.cumsum([(eig[0]/eignsums)*100.0 for eig in sorted(eigenpairs, reverse=True)])

array([  44.286975  ,   53.32040327,   60.80195465,   66.29718352,
         71.44061604,   76.04254625,   79.84856815,   83.21772715,
         86.42480392,   89.27072481,   91.8485655 ,   94.09135577,
         96.07796544,   97.80039334,   99.12162345,  100.        ])

8 seems ok

In [47]:
fit_me=[]
for eignpair in sorted(eigenpairs, reverse=True)[0:8]:
    fit_me.append(eignpair[1].reshape(16,1))

In [43]:
# fit_me= [(eignpair[1].reshape(16,1) for eig in sorted(eigenpairs, reverse=True)[0:8])]

In [48]:
fit_me

[array([[-0.18803934],
        [-0.19357121],
        [ 0.07328808],
        [ 0.51751543],
        [ 0.35845006],
        [ 0.62089874],
        [-0.05713493],
        [-0.00747574],
        [ 0.15602045],
        [-0.03613906],
        [-0.07010134],
        [-0.20296072],
        [ 0.12290505],
        [ 0.07348099],
        [ 0.20525446],
        [-0.04760145]]), array([[ 0.05231849],
        [-0.5860793 ],
        [-0.23045319],
        [ 0.37516036],
        [ 0.12646973],
        [-0.55398342],
        [ 0.01855198],
        [-0.10910015],
        [ 0.10486865],
        [ 0.0799821 ],
        [ 0.0801356 ],
        [-0.13259865],
        [-0.06581724],
        [ 0.07925709],
        [-0.00808044],
        [ 0.26963501]]), array([[-0.29660826],
        [-0.08013044],
        [-0.16884543],
        [-0.01308925],
        [ 0.10990706],
        [ 0.03068335],
        [-0.2133564 ],
        [-0.06665988],
        [-0.17958811],
        [-0.23883742],
        [ 0.56681358],
        [

In [49]:
Pmatrix=np.hstack(fit_me)

In [50]:
pca_data=napolean.dot(Pmatrix)

In [52]:
pca_data.shape

(435, 8)

In [60]:
pca=PCA(n_components=8)
pca_x=pca.fit_transform(napolean)
pca_x

array([[-3.57517112, -0.43829759,  1.00870171, ..., -0.93318399,
        -0.55713373,  0.04677347],
       [-3.69493371,  0.89512838, -1.1943285 , ..., -0.8738653 ,
         0.21938953,  0.26965817],
       [-1.7103028 ,  2.70058387,  0.26750866, ..., -0.03776229,
         1.02671695, -0.99280274],
       ..., 
       [-3.29314631,  0.15144121,  0.33695184, ...,  1.15491098,
         0.4202589 ,  0.5973138 ],
       [-3.4427845 , -0.8753323 , -0.60254499, ...,  0.35237561,
         0.27513523, -0.18348538],
       [-3.72211893,  0.15368173, -0.04647436, ..., -1.04548157,
        -0.40201079,  0.34054779]])

In [57]:
from sklearn.cluster import KMeans

In [59]:
regular_model=KMeans(2)
pca_model=KMeans(2)

In [65]:
def how_many_ones(x):
    ones=[y for y in x if y==1]
    return len(ones)/float(len(x))

In [69]:
regular_model.fit(napolean)
how_many_ones(regular_model.labels_)

0.4735632183908046

In [70]:
pca_model.fit(pca_data)
how_many_ones(regular_model.labels_)

0.4735632183908046

In [80]:
df=pd.read_csv('../datasets/airport_operations.csv')

In [81]:
df.shape

(841, 15)

In [82]:
df

airport  year  departures for metric computation  \
0       ABQ  2004                              53971   
1       ABQ  2005                              51829   
2       ABQ  2006                              49682   
3       ABQ  2007                              53255   
4       ABQ  2008                              49589   
5       ABQ  2009                              42550   
6       ABQ  2010                              42302   
7       ABQ  2011                              42283   
8       ABQ  2012                              39105   
9       ABQ  2013                              35277   
10      ABQ  2014                              33292   
11      ANC  2004                              16503   
12      ANC  2005                              72043   
13      ANC  2006                              75708   
14      ANC  2007                              78741   
15      ANC  2008                              76606   
16      ANC  2009                              67252   
17      ANC  2010                              73089   
18      ANC  2011                              72556   
19      ANC  2012                              70322   
20      ANC  2013                              69984   
21      ANC  2014                              71099   
22      ATL  2004                             477323   
23      ATL  2005                             484570   
24      ATL  2006                             483334   
25      ATL  2007                             491826   
26      ATL  2008                             482903   
27      ATL  2009                             479957   
28      ATL  2010                             469542   
29      ATL  2011                             454954   
..      ...   ...                                ...   
811     TPA  2007                             107523   
812     TPA  2008                             100289   
813     TPA  2009                              83888   
814     TPA  2010                              82346   
815     TPA  2011                              81837   
816     TPA  2012                              80605   
817     TPA  2013                              80603   
818     TPA  2014                              79489   
819     TUS  2004                               7498   
820     TUS  2005                              29803   
821     TUS  2006                              29332   
822     TUS  2007                              32136   
823     TUS  2008                              30267   
824     TUS  2009                              24475   
825     TUS  2010                              24995   
826     TUS  2011                              25149   
827     TUS  2012                              23583   
828     TUS  2013                              22502   
829     TUS  2014                              22589   
830     VNY  2004                               1331   
831     VNY  2005                               5235   
832     VNY  2006                               6142   
833     VNY  2007                               6179   
834     VNY  2008                               4282   
835     VNY  2009                               2986   
836     VNY  2010                               3420   
837     VNY  2011                               4134   
838     VNY  2012                               4753   
839     VNY  2013                               6096   
840     VNY  2014                               7412   

     arrivals for metric computation  percent on-time gate departures  \
0                              53818                           0.8030   
1                              51877                           0.8140   
2                              51199                           0.7983   
3                              53611                           0.8005   
4                              49512                           0.8103   
5                              42704                           0.8341   
6                   

In [83]:
y=df.airport

In [84]:
x=df.drop('airport', axis=1)

In [87]:
y.value_counts()

LAS    11
BUR    11
VNY    11
OAK    11
DCA    11
PVD    11
SEA    11
TPA    11
BWI    11
PHL    11
BUF    11
DAY    11
GYY    11
SAT    11
RDU    11
MEM    11
ISP    11
TEB    11
MHT    11
SJC    11
SWF    11
MKE    11
ONT    11
MSY    11
MIA    11
ATL    11
BOS    11
MDW    11
HNL    11
MSP    11
       ..
SFO    11
SDF    11
PHX    11
LAX    11
IND    11
ORD    11
OGG    11
RSW    11
PIT    11
OMA    11
MCO    11
SLC    11
BDL    11
DFW    11
IAD    11
OXR    11
SJU    11
ABQ    11
AUS    11
HOU    11
HPN    11
RFD    11
CLT    11
EWR    11
BNA    11
PBI    11
DAL    11
JFK    11
PSP     8
SMF     8
Name: airport, dtype: int64

In [88]:
x_tranform=StandardScaler().fit_transform(x)

In [89]:
covariance_matrix=np.cov(x_tranform.T)
covariance_matrix.shape

(14, 14)

In [95]:
a=np.linalg.eig(covariance_matrix)

In [93]:
eignvalues, eigenvectors=np.linalg.eig(covariance_matrix)
eigenpairs=zip(eignvalues, eigenvectors)

In [99]:
eignsums=sum(eignvalues)
eignsums

14.016666666666671

In [100]:
for eig in sorted(eigenpairs, reverse=True):
    print eig[0]/eignsums

0.460415886415
0.307457102817
0.0869143011972
0.0526427153571
0.0364533572683
0.02492412996
0.0119000671954
0.00857696898315
0.00522261699008
0.004579722061
0.000684238706369
0.0001671329354
5.00337606696e-05
1.17263532649e-05


In [101]:
np.cumsum([(eig[0]/eignsums)*100.0 for eig in sorted(eigenpairs, reverse=True)])

array([  46.04158864,   76.78729892,   85.47872904,   90.74300058,
         94.38833631,   96.8807493 ,   98.07075602,   98.92845292,
         99.45071462,   99.90868682,   99.9771107 ,   99.99382399,
         99.99882736,  100.        ])

In [104]:
fit_me=[]
for eignpair in sorted(eigenpairs, reverse=True)[0:5]:
    fit_me.append(eignpair[1].reshape(14,1))
fit_me

[array([[-0.05747614],
        [ 0.05252557],
        [ 0.80890976],
        [-0.38914338],
        [-0.01517249],
        [-0.40455823],
        [-0.03918196],
        [-0.01319762],
        [ 0.14376054],
        [-0.00777298],
        [-0.03107428],
        [-0.02933693],
        [ 0.00229607],
        [ 0.001993  ]]), array([[ 0.11683294],
        [-0.41190929],
        [ 0.16980855],
        [ 0.40257614],
        [-0.12274015],
        [-0.11232074],
        [ 0.29026653],
        [ 0.06082036],
        [ 0.07665943],
        [ 0.03325464],
        [-0.02178517],
        [ 0.02057546],
        [ 0.70799524],
        [ 0.03171276]]), array([[ 0.1164079 ],
        [-0.41158191],
        [ 0.17108429],
        [ 0.40387107],
        [-0.12540936],
        [-0.10989401],
        [ 0.29134664],
        [ 0.06552886],
        [ 0.09065779],
        [ 0.03221664],
        [-0.03615976],
        [-0.02653745],
        [-0.70372734],
        [-0.03443946]]), array([[-0.31455588],
        

In [106]:
Pmatrix=np.hstack(fit_me)

In [107]:
pca_data=x_tranform.dot(Pmatrix)

In [108]:
pca_data.shape

(841, 5)