In [6]:
from sklearn.tree import DecisionTreeClassifier

In [4]:
features=[[140, 1], [130, 1], [150, 0], [170, 0]]
labels=[0, 0, 1, 1]

In [7]:
clf =DecisionTreeClassifier()
clf = clf.fit(features, labels)
print clf.predict([[150, 0]])

[1]


In [8]:
from sklearn.datasets import load_iris

In [23]:
iris=load_iris()

In [10]:
print iris.feature_names

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [11]:
print iris.target_names

['setosa' 'versicolor' 'virginica']


In [12]:
print iris.data[0]

[ 5.1  3.5  1.4  0.2]


In [13]:
print iris.target[0]

0


In [17]:
import numpy as np
from sklearn.model_selection import train_test_split

In [27]:
test_idx=[0, 50, 100]

In [28]:
train_target=np.delete(iris.target, test_idx)
train_data=np.delete(iris.data, test_idx, axis=0)

In [29]:
test_target=iris.target[test_idx]
test_data=iris.data[test_idx]

In [31]:
clf=DecisionTreeClassifier()
clf.fit(train_data, train_target)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [32]:
print test_target

[0 1 2]


In [33]:
print clf.predict(test_data)

[0 1 2]


In [42]:
from sklearn.externals.six import StringIO
import pydot

In [44]:
dot_data=StringIO()
tree.export_graphviz(clf,
                     out_file=dot_data,
                     feature_names=iris.feature_names,
                     class_names=iris.target_names,
                     filled=True,
                     rounded=True,
                     impurity=False)
graph = pydot.graph_from_dot_data(dot_data.getvalue())
graph[0].write_pdf('iris.pdf')

True