In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.datasets import load_breast_cancer


In [7]:
data = load_breast_cancer()

In [8]:
data.keys()

['target_names', 'data', 'target', 'DESCR', 'feature_names']

In [9]:
print data['DESCR']

Breast Cancer Wisconsin (Diagnostic) Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)
        
        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, field
        13 is Radius SE, field 23 is Worst Radius.
 

In [10]:
df = pd.DataFrame(data['data'], columns=data['feature_names'])

In [11]:
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension           ...             worst radius  \
0                 0.07871           ...                    25.38   
1                 0.05667           ...                    24.99   
2                 0.05999           ...                    23.57   
3                 0.09744           ...                    14.91   
4                 0.05883           ...                    22.54   

   worst texture  worst perimeter  worst area  worst smoothness  \
0          17.33           184.60      2019.0            0.1622   
1          23.41           158.80      1956.0            0.1238   
2          25.53           152.50      1709.0            0.1444   
3          26.50            98.87       567.7            0.2098   
4          16.67           152.20      1575.0            0.1374   

   worst compactness  worst concavity  worst concave points  worst symmetry  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   worst fractal dimension  
0                  0.11890  
1                  0.08902  
2                  0.08758  
3                  0.17300  
4                  0.07678  

[5 rows x 30 columns]

In [14]:
y = pd.DataFrame(data['target'], columns=['malignant'])
y.describe()

malignant
count  569.000000
mean     0.627417
std      0.483918
min      0.000000
25%      0.000000
50%      1.000000
75%      1.000000
max      1.000000

In [15]:
from sklearn.cross_validation import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier

In [64]:
decision_tree = DecisionTreeClassifier()
cv_dt=cross_val_score(decision_tree, df, y.malignant, cv=5)

In [65]:
cv_dt

array([ 0.91304348,  0.93043478,  0.92035398,  0.94690265,  0.89380531])

In [58]:
print 'Decision Tree mean accuracy %s' % (cv_dt.mean())

Decision Tree mean accuracy 0.917460561755


In [49]:
bagging_classifier = BaggingClassifier(decision_tree)

In [53]:
cv_bg = cross_val_score(bagging_classifier, df.values,y.malignant, cv=5)

In [54]:
cv_bg

array([ 0.91304348,  0.95652174,  0.96460177,  0.95575221,  0.99115044])

In [57]:
print 'Bagging Classifier mean accuracy %s' % (cv_bg.mean())

Bagging Classifier mean accuracy 0.956213928434


In [59]:
from sklearn.preprocessing import StandardScaler

In [60]:
standard_scaler = StandardScaler()

In [61]:
scaled_xs = standard_scaler.fit_transform(df.values)
scaled_xs

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ..., 
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [75]:
decision_tree = DecisionTreeClassifier()
cv_dt_scaled=cross_val_score(decision_tree, scaled_xs, y.malignant, cv=5)
cv_dt_scaled

array([ 0.91304348,  0.93043478,  0.91150442,  0.95575221,  0.90265487])

In [76]:
cv_dt_scaled.mean()

0.92267795305886879

In [79]:
bagging_classifier = BaggingClassifier(decision_tree)
cv_bg_scaled = cross_val_score(bagging_classifier, scaled_xs,y.malignant, cv=5)
cv_bg_scaled

array([ 0.91304348,  0.94782609,  0.97345133,  0.97345133,  0.94690265])

In [80]:
cv_bg_scaled.mean()

0.95093497499038104

In [81]:
from sklearn.grid_search import GridSearchCV

In [98]:
decision_tree_classifier = DecisionTreeClassifier()
params = {
    'max_depth': [None,1, 2, 3, 4, 5],
    'min_samples_split': [2, 10, 25, 50, 100],
}
grid_search_dt = GridSearchCV(decision_tree_classifier,
                             param_grid=params,
                             cv=5,
#                              verbose=10
                            )
grid_search_dt.fit(df.values, y.malignant)

GridSearchCV(cv=5, error_score='raise',
       estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best'),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'min_samples_split': [2, 10, 25, 50, 100], 'max_depth': [None, 1, 2, 3, 4, 5]},
       pre_dispatch='2*n_jobs', refit=True, scoring=None, verbose=0)

In [99]:
grid_search_dt.best_score_

0.92970123022847095

In [100]:
grid_search_dt.best_estimator_

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=10, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [108]:
bagging_classifier = BaggingClassifier(grid_search_dt.best_estimator_)
params={
    'n_estimators':[4, 10, 50, 100, 1000],
    'max_samples': [.25, .5, 1],
    'max_features': [.25,.5,.75,1],
}
grid_search_bagging = GridSearchCV(bagging_classifier,
                             param_grid=params,
                             n_jobs=-1,
                             cv=5,
#                              verbose=10
                            )
grid_search_bagging.fit(df.values, y.malignant)

GridSearchCV(cv=5, error_score='raise',
       estimator=BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=10, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, sp...n_estimators=10, n_jobs=1, oob_score=False,
         random_state=None, verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=-1,
       param_grid={'n_estimators': [4, 10, 50, 100, 1000], 'max_samples': [0.25, 0.5, 1], 'max_features': [0.25, 0.5, 0.75, 1]},
       pre_dispatch='2*n_jobs', refit=True, scoring=None, verbose=0)

In [110]:
grid_search_bagging.best_score_

0.95957820738137078

In [111]:
grid_search_bagging.best_estimator_

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=10, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=0.75,
         max_samples=0.25, n_estimators=100, n_jobs=1, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [112]:
from sklearn.cross_validation import train_test_split
combined_df = df.join(y)

In [117]:
x_train, x_test, y_train, y_test = train_test_split(df, y.malignant)

In [118]:
print x_train.shape, x_test.shape, y_train.shape, y_test.shape

(426, 30) (143, 30) (426,) (143,)


In [119]:
bagging_classifier = BaggingClassifier(grid_search_dt.best_estimator_)
params={
    'n_estimators':[4, 10, 50, 100, 1000],
    'max_samples': [.25, .5, 1],
    'max_features': [.25,.5,.75,1],
}
grid_search_bagging = GridSearchCV(bagging_classifier,
                             param_grid=params,
                             n_jobs=-1,
                             cv=5,
#                              verbose=10
                            )
grid_search_bagging.fit(x_train, y_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=10, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, sp...n_estimators=10, n_jobs=1, oob_score=False,
         random_state=None, verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=-1,
       param_grid={'n_estimators': [4, 10, 50, 100, 1000], 'max_samples': [0.25, 0.5, 1], 'max_features': [0.25, 0.5, 0.75, 1]},
       pre_dispatch='2*n_jobs', refit=True, scoring=None, verbose=0)

In [120]:
grid_search_bagging.best_score_

0.95774647887323938

In [122]:
best_estimator = grid_search_bagging.best_estimator_

In [123]:
best_estimator

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=10, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=0.25,
         max_samples=0.5, n_estimators=10, n_jobs=1, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [125]:
best_estimator.fit(x_train, y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=10, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=0.25,
         max_samples=0.5, n_estimators=10, n_jobs=1, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [126]:
best_estimator.score(x_test, y_test)

0.95104895104895104

In [128]:
predictions = best_estimator.predict(x_test)

In [127]:
from sklearn.metrics import confusion_matrix, classification_report

In [129]:
confusion_matrix(y_test, predictions)

array([[51,  5],
       [ 2, 85]])

In [130]:
print classification_report(y_test, predictions)

             precision    recall  f1-score   support

          0       0.96      0.91      0.94        56
          1       0.94      0.98      0.96        87

avg / total       0.95      0.95      0.95       143



In [131]:
best_estimator_full_fit = best_estimator
best_estimator_full_fit.fit(df.values, y.malignant)
best_estimator_full_fit.score(df.values, y.malignant)

0.97715289982425313

In [132]:
predictions = best_estimator_full_fit.predict(df.values)

In [133]:
confusion_matrix(y.malignant, predictions)

array([[199,  13],
       [  0, 357]])

In [134]:
print classification_report(y.malignant, predictions)

             precision    recall  f1-score   support

          0       1.00      0.94      0.97       212
          1       0.96      1.00      0.98       357

avg / total       0.98      0.98      0.98       569

