In [2]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

from sqlalchemy import create_engine
engine = create_engine('postgresql://dsi_student:gastudents@dsi.c20gkj5cvu3l.us-east-1.rds.amazonaws.com/titanic')

df = pd.read_sql('SELECT * FROM train', engine)

In [3]:
df.head()

index  PassengerId  Survived  Pclass  \
0      0            1         0       3   
1      1            2         1       1   
2      2            3         1       3   
3      3            4         1       1   
4      4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500  None        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250  None        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500  None        S

# 2. Feature selection

In [4]:
from sklearn.feature_selection import SelectKBest

In [5]:
kbest = SelectKBest(k=5)
kbest

SelectKBest(k=5, score_func=<function f_classif at 0x7f6784b7cd70>)

In [6]:
y=df.Survived

pclass - Dummy
Gender - Dummy
Age    - Good to go
SibSp/Parch - Good to go
Embarked - Dummy

In [15]:
pclass_dumies = pd.get_dummies(df, columns=['Pclass'])
pclass_dumies = pclass_dumies[[1, 2]]
pclass_dumies.columns = ['pclass=1', 'pclass=2']
pclass_dumies.head()

pclass=1  pclass=2
0         1         0
1         2         1
2         3         1
3         4         1
4         5         0

In [16]:
male = df['Sex'].apply(lambda x: 1 if x=='male' else 0)
male.head()

0    1
1    0
2    0
3    0
4    1
Name: Sex, dtype: int64

In [17]:
embarked_dummies = pd.get_dummies(df['Embarked'], prefix='embarked')
embarked_dummies = embarked_dummies[['embarked_C', 'embarked_Q']]
embarked_dummies.head()

embarked_C  embarked_Q
0         0.0         0.0
1         1.0         0.0
2         0.0         0.0
3         0.0         0.0
4         0.0         0.0

In [35]:
analytic_df = pclass_dumies.join(male)
analytic_df = analytic_df.join(df[['Age', 'SibSp', 'Parch']])
analytic_df = analytic_df.join(embarked_dummies)
analytic_df['child'] = analytic_df['Age'].apply(lambda x: 1 if x<12 else 0)
analytic_df['old'] = analytic_df['Age'].apply(lambda x: 1 if x>50 else 0)
analytic_df.head()

pclass=1  pclass=2  Sex   Age  SibSp  Parch  embarked_C  embarked_Q  child  \
0         1         0    1  22.0      1      0         0.0         0.0      0   
1         2         1    0  38.0      1      0         1.0         0.0      0   
2         3         1    0  26.0      0      0         0.0         0.0      0   
3         4         1    0  35.0      1      0         0.0         0.0      0   
4         5         0    1  35.0      0      0         0.0         0.0      0   

   old  
0    0  
1    0  
2    0  
3    0  
4    0

In [36]:
print analytic_df.shape
analytic_df.dropna(inplace=True)
print analytic_df.shape

(891, 10)
(714, 10)


In [39]:
drop_y = analytic_df.join(y, how='left')
drop_y.head()
y=drop_y['Survived']
print y.shape, analytic_df.shape

(714,) (714, 10)


In [42]:
kbest_result_5 = kbest.fit_transform(analytic_df, y)
kbest_result_5

array([[ 0.,  1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       ..., 
       [ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  0.,  0.]])

In [41]:
kbest.scores_

array([  6.13449589e-01,              inf,   2.91287485e+02,
         4.27119493e+00,   2.14599289e-01,   6.25460704e+00,
         2.77276895e+01,   1.75232436e+00,   8.81191517e+00,
         1.13399986e+00])

# 3. Recursive Feature Elimination

In [47]:
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import KFold
from sklearn.feature_selection import RFE

In [49]:
logistic_regression_factory = LogisticRegression()
rfe_factory = RFE(estimator=logistic_regression_factory, step=1)

In [50]:
results_of_rfe = rfe_factory.fit_transform(analytic_df, y)
results_of_rfe

array([[ 0.,  1.,  1.,  0.,  0.],
       [ 1.,  0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       ..., 
       [ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  1.,  0.]])

In [56]:
model_for_kbest_5_columns = LogisticRegression()
model_for_kbest_5_columns.fit(kbest_result_5, y)
model_for_kbest_5_columns.score(kbest_result_5, y)

1.0

In [57]:
results_of_rfe_columns = LogisticRegression()
results_of_rfe_columns.fit(results_of_rfe, y)
results_of_rfe_columns.score(results_of_rfe, y)

1.0